# Generated by Django 3.2.7 on 2021-11-15 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employeedata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=50)),
                ('emp_id', models.IntegerField()),
                ('emp_phno', models.IntegerField()),
                ('emp_cmpname', models.CharField(max_length=60)),
                ('emp_status', models.TextField()),
                ('emp_address', models.TextField()),
            ],
        ),
    ]
